.env-sample

the .env sample file must not be renamed. It is just to get the code inside and put it into a new file .env (ignored by the git) with the particular information of the development environment.

added the .env sample file

---

public/Experience.html

Add Experience.html

---

config/metadata.js
public/css/base.css
public/css/layout.css
public/css/module.css
public/css/state.css
public/js/logic.js
views/index.handlebars
views/layouts/main.handlebars
views/signin.handlebars

Converted the sign in page into a modal that pops up and can be dismissed. Also added more mobile responsiveness with a collapsing/expanding menu on the main page for mobile.

continued mobile response and sign in modal

---

models/experience.js

Add experience association with categories :
experience belongs to categories.

Add experience association with categories

---

.gitignore
models/seeds.sql
models/user.js
routes/apiRoutes-experiences.js
routes/apiRoutes-reviews.js
routes/apiRoutes-users.js
server.js

The attribute name was deleted and added the firstname and lastname instead.

change the user table to add first and last name fields

---

models/seeds.sql

add more experiences on the seeds file

add more experiences on the seeds file

---

models/user.js
package-lock.json
package.json
routes/apiRoutes-auth.js
routes/apiRoutes-experiences.js
routes/apiRoutes-users.js
server.js

implements the user authentication and password crypto. 
changes the users API to adapt the cryptography on the password when creates a new user.

implement the user authentication and password crypto

---

routes/apiRoutes-users.js

added routes the following routes on the users api routes:
- GET all users 
- GET only one user by id

added routes to get all users and to get only one

---

public/js/new-experience.js
routes/apiRoutes-auth.js
routes/apiRoutes-categories.js
routes/apiRoutes-experiences.js
routes/apiRoutes-reviews.js
routes/apiRoutes-users.js
routes/htmlRoutes.js
server.js
views/new-experience.handlebars

Implemented the experiences update and improvements on the file upload.
Now we can see the file uploaded before submitting the experience.
Also is possible to update an experience.

implemented the experiences update and improvements on the file upload

---

library/functions.js
package-lock.json
package.json
routes/apiRoutes-users.js

Implemented api call to send new password to user by email.
Implemented the use of @sendgrid/mail package to send email to user
Implemented the us of generate-password package to generate new random passwords.
Implemented the POST /api/users/resetpwd so the user can request a new password

Implemented api call to send new password to user by email

---

config/metadata.js
public/css/algolia.css
public/css/module.css
public/js/new-experience.js
routes/apiRoutes-experiences.js

Fixed some travis warnings of vars

fixed var to let

---

public/js/logic.js
routes/apiRoutes-users.js
views/layouts/main.handlebars

fixing the var/let warnings and improvements on the sign in modal

fixing the var/let warnings and improvements on the sign in modal

---

routes/apiRoutes-users.js
routes/htmlRoutes.js

Changed the html routes to get the user id from the session variable

changed the html routes to get the user id from the session variable

---

public/js/logic.js

added the api call to authenticate the user

added the api call to authenticate the user

---

public/js/new-experience.js
routes/apiRoutes-experiences.js

fixed the broken code issue on the page that creates/updates an experience

fixed the broked code issue new experience page

---

public/css/module.css
public/js/logic.js
views/layouts/main.handlebars

Improvements on the sign up modal
- Fixed messages that weren't being displayed when it comes from the api on the sign up form.
- Improvements on the css for the messages
- Redirect the user to the sign in modal after signed up

improvements on the sign up modal

---

public/js/logic.js
routes/apiRoutes-experiences.js
routes/apiRoutes-users.js
routes/htmlRoutes.js
views/new-experience.handlebars

bug fixed on the signup
the api call was sending a wrong parameter: "method", instead "type"

bug fixed on the signup

---

routes/apiRoutes-auth.js
server.js

added sign out api route
this api destroy the user session

added sign out api route

---

config/metadata.js
public/js/logic.js
routes/apiRoutes-auth.js
routes/htmlRoutes.js
views/index.handlebars
views/layouts/main.handlebars
views/new-experience.handlebars
views/profile.handlebars
views/user.handlebars

Made changes in all html pages (*.handlebars), including the layout so the buttons stay static on the main layout.
Login and log out is doing without reload the page.

change the html handlebars to let the buttons static

---

public/js/logic.js
views/layouts/main.handlebars

The logout button event wasn't working properly. I organized the code on logic.js and I figured out that the event of the button was assigning inside of other event.
I made huge changes on the logic file just to organize.

fixed bug on the logout button

---

models/seeds.sql
public/js/profile-form.js
server.js
views/experience-form.handlebars

execute the seeds only if its sync force is setup to true

execute the seeds only if its sync force is setup to true

---

README.md

It was missing those packages on the list

Added sendgrid and bcrypt packages and algolia places api on the readme

---

public/js/logic.js
server.js

changed the sync options to not force drop tables when running in production.
show success message when sending the email from the forgot password

changed the sync options to not force drop tables when running in prod.

---

server.js
views/layouts/main.handlebars

Removed the about us link and polish the server.js to not repeat code.

removed the about us link and polish the server.js
